version: "3.8"
#  docker rm -f java-telegram-bot && docker rmi -f java-telegram-bot && docker compose up --build -d
services:
  java-telegram-bot:
    build: .
    image: java-telegram-bot
    container_name: java-telegram-bot
    ports:
      - "8082:8082"
    volumes:
      - ./log:/app/log/
