server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/telegram?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
#SQL 日志 标准输出在控制台
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

bot:
  token: your_telegram_token
  channelId: your_channel_id
  username: your_bot_name
  whitelist: your_telegram_id
deepseek:
  api-key: your_deepseek_api_key
  model: deepseek-reasoner
  base-url: https://api.deepseek.com